- name: Install and start of nginx service
  hosts: servers
  become: yes # -b
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: installed

  - name: start nginx service
    ansible.builtin.service:
      name: nginx
      enabled: yes # here "enabled: true", we can use this one also for enabled
      state: started
  
  - name: checking the nginx service
    ansible.builtin.command: systemctl is-active nginx
      register: nginx_status
      ignore_errors: yes
  
  - name: print the nginx service
    ansible.builtin.debug:
    msg: "nginx service status {{ nginx_status.stdout }}"


  
