- name: creation user and group
  hosts: servers
  become: yes
  tasks:
  - name : creating new user
    ansible.builtin.user: 
      name: rajoli
      state: present

  - name: creating group 
    ansible.builtin.group:
      name: rnk
      state: present

  - name: geatharing system information 
    ansible.builtin.setup:

  - name: Show all gathered facts
    ansible.builtin.debug:
      var: ansible_facts