- name: variables
  hosts: local
  connection: local
  vars: # PLAY level variables, global variables
    NAME: naveen
    LASTNAME: RAJOLI
    NUM: 7263    
  tasks:
  - name: print variables
    # vars: # Task level variables, accessible only with in the task. Task variables can override play level variables. Local variables
    #   NAME: "NAVEEN KUMAR"
    ansible.builtin.debug:
      msg: "my name is {{ NAME }} {{ LASTNAME }} phone number {{ NUM }}"

  - name: print variaables
    ansible.builtin.debug:
      msg: "my name is {{ NAME }} {{ LASTNAME }} phone number {{ NUM }}"

    # below is the command to run the script for local host 
    #                  ansible-playbook -i inventory.ini <script_name>
    # here user and pswd not required bcz its local host 