- name: variables
  hosts: local
  connection: local
  vars_files: # variables fitch from another file var.yaml files 
  - var.yaml  
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "my name is {{ NAME }} {{ LASTNAME }} phone number {{ NUM }}"

  - name: print variables
    ansible.builtin.debug:
    msg: "my name is {{ NAME }} {{ LASTNAME }} phone number {{ NUM }}""