- name: variables from files
  hosts: local
  connection: local
  vars_promt:
  - name: NAME
    promt: "please enter your name"
    private: false # it is not confidential information
  - name: PASSWORD
    promt: "please enter your password"
  - name: NUMBER
    promt: "please enter your pass ****7263"
  tasks:
  - name: printing the information 
    ansible.builtin.debug:
     msg: "name is {{ NAME }} password is {{ PASSWORD }} and number {{ NUMBER }}"

    # practice
    #  var_promt and variables from inventory 