- name: #confidental playbook
  hosts: local
  connection: local
  vars_prompt:
  - name: NAME
    prompt: "please enter your name"
    # private: false #it is not confidential information(if you enable this we can the input information in screen)
  - name: PASSWORD
    prompt: "please enter your password"
    # private: false #it is not confidential information (if you enable this we can the input information in screen)
  - name: NUMBER
    prompt: "please enter your pass ****7263"
    # private: false #it is not confidential information(if you enable this we can the input information in screen)
  tasks:
  - name: printing the information 
    ansible.builtin.debug:
     msg: "name is {{ NAME }} password is {{ PASSWORD }} and number {{ NUMBER }}"

    # practice
    # var_prompt and variables from inventory 
    # variables from inventory 
    # provide variables from command line 