- name: installing apps
  hosts: local
  connection: local
  # become: yes
  tasks:
  - name: installing apps
    ansible.builtin.package:
      name: "{{ item }}"
      sate: installed
    loop:
    - git
    - zip
    - mysql
    - gcc 
