- name: installing packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: installing pacakges
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'git', state: 'present' }
    - { name: 'mysql', state: 'present' }
    - { name: 'gcc', state: 'absent' }
    - { name: 'zip', state: 'absent' }


#     note:
# present:- to install package
# absent:- to uninstall package

